DROP TABLE ITINERARY_ITEMS CASCADE CONSTRAINTS;
DROP SEQUENCE itinerary_items_seq;

CREATE TABLE ITINERARY_ITEMS (
    ItineraryID NUMBER PRIMARY KEY,
    TripID NUMBER NOT NULL,
    ProposalID NUMBER NOT NULL,
    Sequence_Order NUMBER,
     CONFIRMED_AT DATE DEFAULT SYSDATE,
    CONSTRAINT fk_itinerary_trip FOREIGN KEY (TripID) REFERENCES TRIPS(TripID),
    CONSTRAINT fk_itinerary_prop FOREIGN KEY (ProposalID) REFERENCES PROPOSALS(ProposalID)
);

CREATE SEQUENCE itinerary_items_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER itinerary_items_bir
BEFORE INSERT ON ITINERARY_ITEMS
FOR EACH ROW
BEGIN
    SELECT itinerary_items_seq.NEXTVAL INTO :NEW.ItineraryID FROM dual;
END;
/
