DROP TABLE TRIP_MEMBERS CASCADE CONSTRAINTS;

CREATE TABLE TRIP_MEMBERS (
    TripID NUMBER NOT NULL,
    UserID NUMBER NOT NULL,
    Role VARCHAR2(20) DEFAULT 'member',
    Joined_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (TripID, UserID),
    CONSTRAINT fk_tm_trip FOREIGN KEY (TripID) REFERENCES TRIPS(TripID),
    CONSTRAINT fk_tm_user FOREIGN KEY (UserID) REFERENCES USERS(UserID)
);
