DROP TABLE TRIPS CASCADE CONSTRAINTS;
DROP SEQUENCE trips_seq;


CREATE TABLE TRIPS (
    TripID NUMBER PRIMARY KEY,
    Trip_Name VARCHAR2(100) NOT NULL,
    Join_Code VARCHAR2(10) UNIQUE NOT NULL,
    Budget NUMBER(10,2),   
    Start_Date DATE,
    End_Date DATE,
    Created_By NUMBER NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trips_user FOREIGN KEY (Created_By) REFERENCES USERS(UserID)
);


-- generate the ID
CREATE SEQUENCE trips_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trips_bir
BEFORE INSERT ON TRIPS
FOR EACH ROW
BEGIN
    SELECT trips_seq.NEXTVAL INTO :NEW.TripID FROM dual;
END;
/
