DROP TABLE POLLS CASCADE CONSTRAINTS;
DROP SEQUENCE polls_seq;

CREATE TABLE POLLS (
    PollID NUMBER PRIMARY KEY,
    TripID NUMBER NOT NULL,
    Created_By NUMBER NOT NULL,
    Title VARCHAR2(200),
    Deadline TIMESTAMP,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Is_Open NUMBER(1) DEFAULT 1,
    CONSTRAINT fk_poll_trip FOREIGN KEY (TripID) REFERENCES TRIPS(TripID),
    CONSTRAINT fk_poll_user FOREIGN KEY (Created_By) REFERENCES USERS(UserID)
);

--generate the pollID
CREATE SEQUENCE polls_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER polls_bir
BEFORE INSERT ON POLLS
FOR EACH ROW
BEGIN
    SELECT polls_seq.NEXTVAL INTO :NEW.PollID FROM dual;
END;
/
