DROP TABLE POLL_OPTIONS CASCADE CONSTRAINTS;
DROP SEQUENCE poll_options_seq;


CREATE TABLE POLL_OPTIONS (
    OptionID NUMBER PRIMARY KEY,
    PollID NUMBER NOT NULL,
    ProposalID NUMBER NOT NULL,
    CONSTRAINT fk_po_poll FOREIGN KEY (PollID) REFERENCES POLLS(PollID),
    CONSTRAINT fk_po_prop FOREIGN KEY (ProposalID) REFERENCES PROPOSALS(ProposalID)
);

--generate poll option IDs

CREATE SEQUENCE poll_options_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER poll_options_bir
BEFORE INSERT ON POLL_OPTIONS
FOR EACH ROW
BEGIN
    SELECT poll_options_seq.NEXTVAL INTO :NEW.OptionID FROM dual;
END;
/
