DROP TABLE VOTES CASCADE CONSTRAINTS;
DROP SEQUENCE votes_seq;

CREATE TABLE VOTES (
    VoteID NUMBER PRIMARY KEY,
    OptionID NUMBER NOT NULL,
    UserID NUMBER NOT NULL,
    Voted_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vote_option FOREIGN KEY (OptionID) REFERENCES POLL_OPTIONS(OptionID),
    CONSTRAINT fk_vote_user FOREIGN KEY (UserID) REFERENCES USERS(UserID),
    CONSTRAINT unq_user_option UNIQUE (UserID, OptionID)
);


CREATE SEQUENCE votes_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER votes_bir
BEFORE INSERT ON VOTES
FOR EACH ROW
BEGIN
  IF :NEW.VoteID IS NULL THEN
    SELECT votes_seq.NEXTVAL INTO :NEW.VoteID FROM dual;
  END IF;
END;
/
