DROP TABLE COST_ESTIMATES CASCADE CONSTRAINTS;
DROP SEQUENCE cost_estimates_seq;

CREATE TABLE COST_ESTIMATES (
    CostID NUMBER PRIMARY KEY,
    ProposalID NUMBER NOT NULL,
    Created_By NUMBER NOT NULL,
    Estimated_Total_Cost NUMBER(10,2),
    Cost_Per_Person NUMBER(10,2),
    Num_People NUMBER,
    Notes VARCHAR2(300),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cost_prop FOREIGN KEY (ProposalID) REFERENCES PROPOSALS(ProposalID),
    CONSTRAINT fk_cost_user FOREIGN KEY (Created_By) REFERENCES USERS(UserID)
);


CREATE SEQUENCE cost_estimates_seq START WITH 100 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER cost_estimates_bir
BEFORE INSERT ON COST_ESTIMATES
FOR EACH ROW
BEGIN
    SELECT cost_estimates_seq.NEXTVAL INTO :NEW.CostID FROM dual;
END;
/
